Repository LLK/scratch-svg-renderer, pull requests merged in 2018-05, with the labels that each got.

#15 Webpack 4
  package.json
  webpack.config.js
Labels: pr needs-review

#16 Break transformText into new functions that can be exported
  src/font-converter.js
  src/font-inliner.js
  src/index.js
  src/svg-renderer.js
Labels: pr - needs review

#21 Build scratch-render-fonts using babel loader
  webpack.config.js
Labels: pr - needs review

#22 Compat mode
  src/svg-renderer.js
Labels: blocked, pr - good to merge

#26 Fix the default line height. In 2.0 the default is 1
  src/svg-renderer.js
Labels: pr - needs review

#29 Font calibration
  src/svg-renderer.js
Labels: pr - good to merge

#17 Use src/index for browser entry point
  package.json
  webpack.config.js
Labels: pr - good to merge
